#/bin/sh

picom -b & # compisitor
dunst & # notification server 
trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --transparent true --alpha 0 --tint 0x21262e --height 20 & # system tray
nm-applet & # network manager 
volumeicon & # volume icon 
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock & # auto screen locker
set-wallpaper &
exec xmonad
